### ISSUE TITLE
Aegisub for Android

### ISSUE THREAD

**Issue by Wjsfj51najdk** [Aegisub/Aegisub#101]
Please built an android version.This is really nice software

**Comment by Wjsfj51najdk** [comment]
Sorry for late reply
I need to translate and make ssa files with android. Ageisub is easy to use and I can add colors and italic to subtitles using ageisub.I think it would great and easy for us if ageisub available android version.Thanks

**Comment by aytimothy** [comment]
A mobile screen is just waay too small for that sort of stuff.

**Comment by Seekladoom** [comment]
You can consider porting aegisub to Android with kotlin, The best kotlin development resource in the world is here：
https://github.com/KotlinBy/awesome-kotlin
