### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by scx** [Aegisub/Aegisub#102]
I created the flatpak package for Aegisub.
https://github.com/scx/aegisub-flatpak#aegisub-flatpak

I am in the process of submitting it to the Flathub repo.
https://github.com/flathub/flathub/pull/752
https://github.com/scx/flathub/tree/org.aegisub.Aegisub

It would be nice if the author decided to participate in the further development of this flatpak package.
First of all, I would ask you to verify AppData file:
https://github.com/scx/flathub/blob/org.aegisub.Aegisub/org.aegisub.Aegisub.appdata.xml

**Comment by CoffeeFlux** [comment]
I'm open to a Flatpak or AppImage in the TSTools repo, but closing here.
