### ISSUE TITLE
Where are build/install instructions for Linux?

### ISSUE THREAD

**Issue by OnkelTem** [Aegisub/Aegisub#104]
See subject

**Comment by CoffeeFlux** [comment]
They're just a simplified version of the OSX build instructions: install the dependencies via your package manager, then run `autoreconf`, `./configure`, and `make`. You can also check out the AUR aegisub-git PKGBUILD if something is unclear.

With that said, while I don't speak for the project, being an ass in the Github issues is generally not productive. No one's required to offer free support, and snark is definitely not going to increase the odds of that happening ;)

**Comment by darealshinji** [comment]
You _may_ have to apply this patch before it builds:
https://github.com/Aegisub/Aegisub/pull/38/files

Other than that it's just installing dependencies and `./autogen.sh && ./configure && make`
