### ISSUE TITLE
CPS should include white space and punctuation

### ISSUE THREAD

**Issue by franontanaya** [Aegisub/Aegisub#117]
As of 3.2.2 CPS is calculated excluding white space. The general convention is to count them. For a recent example:

https://partnerhelp.netflixstudios.com/hc/en-us/articles/115001352212-How-is-reading-speed-measured-Do-punctuation-and-spaces-count-

> Spaces and punctuation are counted by the software towards both the character count and the reading speed limit.

**Comment by tgoyne** [comment]
This is customizable on the Interface page of the preferences.

There are shockingly few "general conventions" around character counts that are actually consistent around the world. AFAICT the people writing broadcast standards in various countries many decades ago just picked what they considered to be the obvious choice, with the end result being that every permutation you can imagine is mandated somewhere.
