### ISSUE TITLE
Error compiling in ubuntu 19.04

### ISSUE THREAD

**Issue by SSgumS** [Aegisub/Aegisub#123]
Hi
After I upgraded to ubuntu 19.04, I couldn't install aegisub from ubuntu default repository and [this](https://launchpad.net/~alex-p/+archive/ubuntu/aegisub) source because of libboost mismatch (I don't know really how to solve it. I reinstalled the exact version again but it didn't solve any problems).
After that, I decided to compile aegisub from source myself. I downloaded the latest release (3.2.2) and run _configure_ successfully and then entered _make_ and I got this error:
`g++ -MMD -MP -I/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/include -I/home/ssgums/Downloads/Temp/aegisub-3.2.2/ -fPIC -I/usr/include -DBOOST_SYSTEM_NO_DEPRECATED -I/home/ssgums/Downloads/Temp/aegisub-3.2.2/vendor/luajit/include -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -pipe -g -std=c++11 -Wno-c++11-narrowing -Wno-unused-local-typedefs -O3  -include /home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/lagi_pre.h   -c -o /home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.o /home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp: In lambda function:
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp:39:12: error: ‘BreakIterator’ has not been declared
   bi.reset(BreakIterator::createCharacterInstance(Locale::getDefault(), status));
            ^~~~~~~~~~~~~
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp:39:51: error: ‘Locale’ has not been declared
   bi.reset(BreakIterator::createCharacterInstance(Locale::getDefault(), status));
                                                   ^~~~~~
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp: In function ‘size_t {anonymous}::count_in_range(Iterator, Iterator, int)’:
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp:61:46: error: ‘BreakIterator’ has not been declared
  for (auto end = character_bi.next(); end != BreakIterator::DONE; pos = end, end = character_bi.next()) {
                                              ^~~~~~~~~~~~~
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp: In function ‘size_t agi::IndexOfCharacter(const string&, size_t)’:
/home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.cpp:146:14: error: ‘BreakIterator’ has not been declared
   if (end == BreakIterator::DONE)
              ^~~~~~~~~~~~~
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-c++11-narrowing’
make: *** [Makefile.target:100: /home/ssgums/Downloads/Temp/aegisub-3.2.2/libaegisub/common/character_count.o] Error 1
`

What can I do to solve the problem?

**Comment by wangqr** [comment]
3.2.2 is a really old release. Are you able to build from git master? You may use [AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=aegisub-git#n68) as a reference to build

**Comment by wangqr** [comment]
It should have been fixed in d4461f65be5aa440506bd23e90e71aaf8f0ebada. So if you decided to use the master branch, `CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'` is not required.

**Comment by SSgumS** [comment]
> It should have been fixed in [d4461f6](https://github.com/Aegisub/Aegisub/commit/d4461f65be5aa440506bd23e90e71aaf8f0ebada). So if you decided to use the master branch, `CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'` is not required.

Thanks a lot. I didn't try to built it from git master. You are right. Based on the commit you mentioned, the problem will solve if I do this.
Before I read your comments, fortunately I tried building from [aniolm9 | Aegisub](https://github.com/aniolm9/Aegisub) fork and It solved my problem.
Thanks again :+1:
