### ISSUE TITLE
Feature request: Text Blend Mode

### ISSUE THREAD

**Issue by SparkYaro** [Aegisub/Aegisub#124]
I'm sorry if this feature was already implemented, but after several years working with Aegisub I haven't found a working "blend mode" for my subtitles when I needed it.
I think it could be very handy in the next releases, with the `\blend` tag.
Example of an Aegisub line: `{\blend Difference} Text on a flower`
Showing a picture for reference!
![Blend modes](https://user-images.githubusercontent.com/42842135/60127945-c56fc780-9791-11e9-98f4-0ec542ac02ce.png)

**Comment by CoffeeFlux** [comment]
This isn't an Aegisub concern; it's dependent on the underlying ASS format and renderers implementing it. You could try filing an issue against libass if you want to see this happen.

**Comment by SparkYaro** [comment]
> 
> 
> This isn't an Aegisub concern; it's dependent on the underlying ASS format and renderers implementing it. You could try filing an issue against libass if you want to see this happen.

Thank you for clarifying it! I'll open a libass issue then.
