### ISSUE TITLE
How to show "\N" in subtitle？

### ISSUE THREAD

**Issue by Mapaler** [Aegisub/Aegisub#127]
![Screenshot 2019-07-05 15 47 01](https://user-images.githubusercontent.com/6565860/60706490-2b9bdd80-9f3c-11e9-98ee-c935a96689e0.png)
The path contains the "\N", I tried many ways that failed. Is there an escape?

**Comment by FichteFoll** [comment]
No, but try `\{}N`.

**Comment by Mapaler** [comment]
@FichteFoll Thanks, this is a teaching video, aimed at newbies, so the forward slashes is more in line with usage habits.

**Comment by FichteFoll** [comment]
Here's an alternative solution along with further discussion of why there are no escape codes at the moment: https://github.com/libass/libass/issues/194#issuecomment-351902555
