### ISSUE TITLE
Win64: Add support 64 bit avisynth

### ISSUE THREAD

**Issue by seiya-git** [Aegisub/Aegisub#129]
Please, add support 64 bit avisynth in 64 bit builds

**Comment by wangqr** [comment]
Which version are you using? I can build 64 bit version with Avisynth+ r2772 without issue

**Comment by seiya-git** [comment]
64bit r8942, and I can't select avisynth at all

**Comment by wangqr** [comment]
Yeah, the chunk builds at http://plorkyeran.com/aegisub/ does not enable avisynth. You may need to build yourself. Make sure the `WITH_AVISYNTH` macro is defined in the `acconf.h`, which is generated by `configure`.

Or you may try my build at https://ftp.wangqr.tk/aegisub/, which is built from [my fork](https://github.com/wangqr/Aegisub).

**Comment by seiya-git** [comment]
@wangqr, thanks, it's working!
