### ISSUE TITLE
Migrate the build system and dependency management to CMake and Conan

### ISSUE THREAD

**Issue by cqjjjzr** [Aegisub/Aegisub#153]
Hi.

When I work on Aegisub, I found the dependency management of Aegisub so painful(especially for Windows, since they used Visual Studio to build all dependencies and those .vcxprojs have problems for Visual Studio 2019), so I'm now working on migrating all the dependencies to Conan to avoid manual dependency configuring. 

@wangqr has written the CMake build files which requires the develops to resolve dependencies themselves.

I've already managed to build the whole project successfully on Windows using CMake and Conan. You can find my work here: https://github.com/cqjjjzr/Aegisub/tree/dev-cj

Using CMake + Conan has those advantages:

- United dependencies on all platforms and amazing cross-platform&IDE&toolchain compatibility
- Handy: one-click dependence resolving
- Much easier to maintain compared to autotools stuff and vcxprojs.

Cheers,
Charlie Jiang

**Comment by FichteFoll** [comment]
Just a headsup that there is an existing config for meson in a fork that works on Linux and can (almost?) cross-compile to Windows, but iirc still needs vscp.

https://github.com/TypesettingTools/Aegisub/tree/meson

**Comment by milahu** [comment]
> https://github.com/TypesettingTools/Aegisub/tree/meson

moved to https://github.com/TypesettingTools/Aegisub
has `meson` build tool, which is using `cmake`

abandoned fork with `cmake` https://github.com/Ristellise/AegisubDC
problem: the git repo is seriously bloated:

```
$ du -sh src/ vendor/
5.7M	src/
1.1G	vendor/
```

for a debloated version, see my fork https://github.com/milahu/AegisubDC
