### ISSUE TITLE
Potential auto-typesetting

### ISSUE THREAD

**Issue by champ8644** [Aegisub/Aegisub#162]
Is there any APIs or scripts that would help me get pixel color from the video? eg. `PixelColorGet(frame, x, y)`
And a way to loop through video frame by frame? So I can make a new macro somewhat like this
`for (let i = video.beginFrame; i<video.endFrame; i++) {
If (isBeginningOfNewLine(pixelColorGet(video.frame[i])))
    subtitles.append(line);
}`
Because in my projects I can create some fixed conditions by using pixel color of the video that would indicate that there would be a new subtitle at specific times. Currently I’m doing manual typesetting and this is pretty much tedious jobs which I think I could have done it in a better way.
Thanks.

**Comment by wangqr** [comment]
If you are trying to fully automate some specific use case according to certain indicating pixel, I would suggest you try [OpenCV](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_gui/py_video_display/py_video_display.html).

If you just want to extract hard sub from video, there is fully automated tool esrXP. Or the cqjjjzr fork does add a function to Aegisub to automatically set the begin/end time of a single line according to pixel color change, see https://github.com/wangqr/Aegisub/issues/7 and [try the binary build](https://github.com/wangqr/Aegisub/releases/tag/v3.3.0).
