### ISSUE TITLE
Cannot find instruction on installing Aegissub on Linux (Ubuntu)

### ISSUE THREAD

**Issue by jasomdotnet** [Aegisub/Aegisub#163]
Cannot find instruction on installing Aegissub on Linux (Ubuntu). Are there any? If yes, where is a link.

**Comment by kinow** [comment]
There's a PR open for that. Maybe you'd like to take a look if that works for your environment? https://github.com/Aegisub/Aegisub/pull/159

**Comment by jasomdotnet** [comment]
Aside of PR are two letters from alphabet, what else they stand for in your universe, @kinow?

**Comment by wangqr** [comment]
PR stands for pull request. The #159 is the link to that pr

**Comment by jesusrivas89** [comment]
> Cannot find instruction on installing Aegissub on Linux (Ubuntu). Are there any? If yes, where is a link.

**Here:** http://ubuntuhandbook.org/index.php/2018/08/how-to-install-aegisub-subtitle-editor-in-ubuntu-18-04/

this ppa serves from Xenial to Eoan
