### ISSUE TITLE
Unfamiliar tag parameter

### ISSUE THREAD

**Issue by knaik95** [Aegisub/Aegisub#169]
This isn't really an issue from a back-end code standpoint but I was reading an .ass file and found `\fr!temp.angle11!` in one of the Dialogue lines. What kind of parameter is that?

**Comment by FichteFoll** [comment]
`temp` must be a custom variable (table) defined somewhere earlier in a code line.

**Comment by wangqr** [comment]
`\fr` is an ASS tag that describes text rotation. See http://docs.aegisub.org/3.2/ASS_Tags/ .

`!temp.angle11!` is a Lua code snippet surrounded by a pair of exclamation marks. They will be evaluated and expanded if you click `Automation > Apply karaoke template` from menu. See http://docs.aegisub.org/manual/Karaoke_Templater_Reference:_Template_execution_rules_and_order .

**Comment by knaik95** [comment]
> `\fr` is an ASS tag that describes text rotation. See http://docs.aegisub.org/3.2/ASS_Tags/ .
> 
> `!temp.angle11!` is a Lua code snippet surrounded by a pair of exclamation marks. They will be evaluated and expanded if you click `Automation > Apply karaoke template` from menu. See http://docs.aegisub.org/manual/Karaoke_Templater_Reference:_Template_execution_rules_and_order .

Ohhh, that makes sense. It was too unique to be an accident so I was confused (I don't know Lua). What happens if you just leave it in the file for reading by a video player?

Also, this is an actual issue I'm having with the software. I rewrote the Resolution Resampler and all its dependencies in Python. When I push a file through it and attempt to open it with Aegisub, I get this:

![CWaPaD1](https://user-images.githubusercontent.com/8051679/73982992-636c6880-4903-11ea-9d87-7071385ccb78.png)

I searched the repo but couldn't find where the error is being thrown.

**Comment by wangqr** [comment]
[Google](https://www.google.com/search?q=bad+lexical+cast%3A+source+type+value+could+not+be+interpreted+as+target) says that the error message comes from `boost::lexical_cast`

**Comment by knaik95** [comment]
> [Google](https://www.google.com/search?q=bad+lexical+cast%3A+source+type+value+could+not+be+interpreted+as+target) says that the error message comes from `boost::lexical_cast`

So there's no way to trace it back to what part doesn't agree with lexical_cast?

**Comment by wangqr** [comment]
> So there's no way to trace it back to what part doesn't agree with lexical_cast?

You need a debugger to set breakpoint on that call or uncaught exception. Any modern debugger should work.

**Comment by knaik95** [comment]
> > So there's no way to trace it back to what part doesn't agree with lexical_cast?
> 
> You need a debugger to set breakpoint on that call or uncaught exception. Any modern debugger should work.

Do I have to download the aegisub source code and compile boost for that?

**Comment by wangqr** [comment]
> What happens if you just leave it in the file for reading by a video player?

Those lua code is not a part of ASS. It's just a way to automate things. They need to be executed to produce plain ASS which can be used in any other tool.

> Do I have to download the aegisub source code and compile boost for that?

I think I've misunderstood something. Aren't you already modifying Aegisub source code when you "rewrote the Resolution Resampler"?

**Comment by knaik95** [comment]
> Those lua code is not a part of ASS. It's just a way to automate things. They need to be executed to produce plain ASS which can be used in any other tool.

The lua snippets not being a part of ASS makes me wonder what happens when read by an unsuspecting parser. I tried it and it just seems to ignore it so I guess it's safe for me to ignore it, too.

> I think I've misunderstood something. Aren't you already modifying Aegisub source code when you "rewrote the Resolution Resampler"?

Maybe 'reimplemented' is more appropriate? I just read the code from this repo and built a Python version from scratch.

**Comment by wangqr** [comment]
> I just read the code from this repo and built a Python version from scratch.

So how is the result feeded into Aegisub? Is it generating a new ASS file or somehow intergrated into Aegisub?

**Comment by knaik95** [comment]
Yeah it's generating a new file and I just try opening it with the actual
Aegisub program. It shows that error dialog then just closes.

**Comment by wangqr** [comment]
Can you provide the generated file (i.e. the file causing Aegisub crash)?

**Comment by knaik95** [comment]
> Can you provide the generated file (i.e. the file causing Aegisub crash)?

Here's the file with a .txt extension at the end.
[resample_test.ass.txt](https://github.com/Aegisub/Aegisub/files/4194740/resample_test.ass.txt)

**Comment by wangqr** [comment]
![img](https://user-images.githubusercontent.com/8182182/74374957-72dd2d00-4dad-11ea-8a04-44425fc06055.png)

Just tried to open that file in Excel as csv. The file is malformed and certain fields are missing. Looks like most rows are missing the `Name` field, and some even missing `Text`.

**Comment by knaik95** [comment]
> ![img](https://user-images.githubusercontent.com/8182182/74374957-72dd2d00-4dad-11ea-8a04-44425fc06055.png)
> 
> Just tried to open that file in Excel as csv. The file is malformed and certain fields are missing. Looks like most rows are missing the `Name` field, and some even missing `Text`.

That's a good trick. I would've never thought of that. And...

OMG it was **one** line of code that messed everything up.

I had
```
def append_str(main, string):
	if not string: **return main**
	return main + string + ","
```

When it should've been
```
def append_str(main, string):
	if not string: **return main + ","**
	return main + string + ","
```

Now, the file opens up just fine. Thanks so much!
