### ISSUE TITLE
Updated website and new release

### ISSUE THREAD

**Issue by Arno500** [Aegisub/Aegisub#176]
When looking at the main aegisub.org website, we can think the project is dead.
But it's not, and it's hard for fansubbers to compile their own version of Aegisub.
As mentionned in #76, it would be awesome to have a new shiny release ready to be put on a new website (including a new forum maybe, a new News section if needed and even new documentation with something like Readthedocs).
I'm willing to contribute to the new website if needed.

**Comment by denizdogan** [comment]
Who is the person responsible for updating these things? Six years since the last official release is a very long time. Is there even a maintainer anymore?

**Comment by tudos4** [comment]
There is a developed fork: https://github.com/wangqr/Aegisub

**Comment by FichteFoll** [comment]
You can follow #214 now.
