### ISSUE TITLE
accel modifier details

### ISSUE THREAD

**Issue by true-meowmeow** [Aegisub/Aegisub#179]
Can you show the accel modifier code?

\t (t1 , t2 , accel, ..)
How it works?

**Comment by wangqr** [comment]
See ASS spec at http://moodub.free.fr/video/ass-specs.doc or Aegisub manual at http://docs.aegisub.org/3.2/ASS_Tags/

**Comment by true-meowmeow** [comment]
Yes, but can you show me the formula itself?

**Comment by true-meowmeow** [comment]
Yes, but can you show me the formula itself?

вт, 7 апр. 2020 г. в 15:16, wangqr <notifications@github.com>:

**Comment by wangqr** [comment]
Which formula are you looking for? Isn't it already in the document?
![img](https://user-images.githubusercontent.com/8182182/78668241-525eba00-78a8-11ea-9924-3a348b421d17.png)
