### ISSUE TITLE
Typo in luabins.c and lpeg.c

### ISSUE THREAD

**Issue by plater** [Aegisub/Aegisub#182]
vendor/luabins/src/luabins.c and libaegisub/lua/modules/lpeg.c both have type luaL_reg instead of the correct type defined in lauxlib.h lual_Reg.
It's nice to see that this package is still under development .
[luaL_Reg-not-luaL_reg.patch.txt](https://github.com/Aegisub/Aegisub/files/4557520/luaL_Reg-not-luaL_reg.patch.txt)

**Comment by wangqr** [comment]
It's not a typo. In Lua 5.0 it is named `luaL_reg`, and was [renamed to `luaL_Reg` in Lua 5.1](http://lua-users.org/wiki/CompatibilityWithLuaFive). Fixing this is a good thing though.

**Comment by wangqr** [comment]
Also, as this is a luabins issue, you should also report here: https://github.com/agladysh/luabins
