### ISSUE TITLE
Incorrect font rendering

### ISSUE THREAD

**Issue by clustor** [Aegisub/Aegisub#184]
Here is a simple example showing the issue . The word "ద్రావిడ" renders incorrectly in the video preview. I am using this well used font https://fonts.google.com/specimen/Mallanna?subset=telugu. The font itself has no issue in other editors. Same issue exists with every other language font I tried. 

<img width="871" alt="image" src="https://user-images.githubusercontent.com/15720802/81483367-b22fe400-920b-11ea-8447-24b5f4daa5be.png">

It seems like some library that Aegisub uses has an issue. I am on MacOS Catalina running Aegisub 3.2.2. 

Thanks

**Comment by wangqr** [comment]
Aegisub uses libass on non-Windows OSes to render the subtitle. The official build uses libass 0.13.1.

I cannot understand that language, nor can I tell whether it is rendered correctly. I made an screenshot rendered by libass 0.14.0. Is this correct?
![img](https://user-images.githubusercontent.com/8182182/81486317-e8785e00-9221-11ea-8b1e-1a1889943c01.png)

**Comment by clustor** [comment]
Yes. This is rendered correctly indeed. Do I need to build the app manually for it to use latest libass? I already have libass 0.14.0_1 on my machine with homebrew.

**Comment by wangqr** [comment]
Yes, you need to build Aegisub from source to use the latest libass. The build guide is available in README.

Alternatively, I made nightly build from [my fork](https://github.com/wangqr/Aegisub/) which has some not-merged changes. The build uses libass 0.14.0 and is available at https://ftp.wangqr.tk/aegisub/aegisub-macos-20200507-r9118.dmg

**Comment by clustor** [comment]
This build fixes the issue.
