### ISSUE TITLE
snap support

### ISSUE THREAD

**Issue by Fuseteam** [Aegisub/Aegisub#189]
currently aegisub seems to be missing from the repos on ubuntu, due to some issues. with snap we can ensure the program can run well even in further releases

**Comment by Fuseteam** [comment]
does this mean we now have an official snap?

**Comment by CoffeeFlux** [comment]
No, but I'm closing out issues in this repo that aren't going to happen soon. We'll probably publish a flatpak or appimage at some point, but I'd also expect the program to be added to Ubuntu with the new stable.

**Comment by Fuseteam** [comment]
ah fair, tho there is an unofficial snap already, so it might not be too difficult to get the snap going (there is a procedure to take over unofficial snaps) not quite sure about the flatpak side tho that might be similar. I wouldn't recommend appimages as those rely on the outdated fuse2 library which hasn't been maintained since 2018
