### ISSUE TITLE
Aegisub is not compatible with the new FFMS (ffms2 2.40)

### ISSUE THREAD

**Issue by Jolly979** [Aegisub/Aegisub#198]
After upgrading my Linux distro, i ran Aegisub and got this error

`aegisub-3.2: symbol lookup error: aegisub-3.2: undefined symbol: FFMS_DoIndexinga`

So i had to downgrade from `ffms2` 2.40 package to `ffms2` 2.23.1

**Comment by wangqr** [comment]
I have no issue building and running aegisub git version with ffms2 2.40 on Archlinux. Can you provide more details on what distro you are using and how aegisub is built?

**Comment by Jolly979** [comment]
Manjaro Linux
`pacman -S aegisub`

**Comment by wangqr** [comment]
According to https://bugs.archlinux.org/task/67950 , you may need to use the `aegisub-git` in AUR
