### ISSUE TITLE
Feature request: Dark theme

### ISSUE THREAD

**Issue by MustDy** [Aegisub/Aegisub#201]
As I am working with subtitles mostly during night, it would be great to have an option to change main panel color to dark one. 
Current option setup actually supports only sub panels color editing, which still leaves half of the UI untouched. 
I have seen couple of screenshots with aegisub with dark UI in Ubuntu, which could directly control application main colors. 

Like this:
![photo_2020-10-18_21-44-18](https://user-images.githubusercontent.com/18714743/96379039-e256b800-1197-11eb-82ff-33fe74a01240.jpg)

Missing this feature from windows edition. Night warriors of funsubbing community would appritiate it.

**Comment by siceyn** [comment]
You can use third-party windows themes to have aegisub completely dark (after configuring colors in preferences). See https://lmgtfy.app/?q=deviantart+windows+10+themes

**Comment by MustDy** [comment]
> You can use third-party windows themes to have aegisub completely dark (after configuring colors in preferences). See https://lmgtfy.app/?q=deviantart+windows+10+themes

Want to mention, that windows themes controls only UWP applications UI. 
Just as an example: 

![image](https://user-images.githubusercontent.com/18714743/96734190-f16d7e00-13c2-11eb-8404-72edc7d79a67.png)

As you could see, explorer (as a UWP app) is controlled by theme settings, aegisub - not.

**Comment by siceyn** [comment]
Default windows theme does not, that's why I gave you a link to search deviantart.

**Comment by MustDy** [comment]
Okay, could confirm. Still think this feature is needed to be built-in, but as workaround exists, could be left as it is.

**Comment by ilko-k** [comment]
You're running a very outdated version of Aegisub, is this voluntary ?

**Comment by iammursalin** [comment]
well... after 1 year later. any updates?

**Comment by MustDy** [comment]
Custom themes are working. 
It requires some system modifications, as well as it applies to technically everything - but yes, it is an option. 
Still think that night theme, especially in 2021 is a must for an app, but there is a workaround. 
Closing the issue.

**Comment by YuenSzeHong** [comment]
@MustDy so can you provide information on the work around, for those stumbling upon this issue when googling on this feature? if you have got that working (beg)

**Comment by siceyn** [comment]
Step 1- Go to deviantart
Step 2- Search for Windows 10/11 dark themes
Step 3- Install the theme you like by following the instructions given in
the description.
Step 4- After installation, create a color palette in aegisub that
compliments your themes color scheme.
Step 5- Profit.

**Comment by YuenSzeHong** [comment]
@siceyn how to create the color palette

**Comment by garret1317** [comment]
options -> interface -> colours -> click the colours and change them to ones you like
![](https://user-images.githubusercontent.com/76261416/174495489-40172db0-1161-46b0-8fc9-c8c2263aa98c.png)

**Comment by YuenSzeHong** [comment]
> options -> interface -> colours -> click the colours and change them to ones you like
> ![](https://user-images.githubusercontent.com/76261416/174495489-40172db0-1161-46b0-8fc9-c8c2263aa98c.png)
> 

so can't switch between dark mode and light mode easily

**Comment by FichteFoll** [comment]
You can switch out the config file that stores the colors when you want to switch themes, but yes, you cannot store multiple color schemes currently and have them change dynamically based on your system theme setting, for example. That should be in a different issue.

**Comment by ghost** [comment]
Is it possible to do something similar to this on MacOS?
