### ISSUE TITLE
Need Help (Makefile.target Error)

### ISSUE THREAD

**Issue by siceyn** [Aegisub/Aegisub#203]
I have been trying to compile Aegisub with hwaccel enabled in ffmpeg configuration since yesterday, I fixed a lot of problems but now make gives me this error message:

Makefile.target:100: recipe for target '/home/sicey/Downloads/Aegisub/src/libresrc/libresrc.o' failed
make: *** [/home/sicey/Downloads/Aegisub/src/libresrc/libresrc.o] Error 1

I know literally nothing about c++ or makefile, so I wanted to ask for help here.

**Comment by samoht0** [comment]
> I have been trying to compile Aegisub with hwaccel enabled in ffmpeg configuration since yesterday [...]

Hardware support in FFMS2 seems unsupported. I doubt, this is fixable in aegisub's build system.

https://github.com/FFMS/ffms2/issues/337
