### ISSUE TITLE
Bug/Crash in MacOS Catalina

### ISSUE THREAD

**Issue by UserIsCool** [Aegisub/Aegisub#204]
**Please update the software!** 
The software is **always crash** when i **import video**. 
**Please fix this!**

**Comment by UserIsCool** [comment]
Screenshot:
<img width="550" alt="Jepretan Layar 2020-11-06 pukul 18 52 35" src="https://user-images.githubusercontent.com/74053141/98363302-541c7600-2061-11eb-8fae-d917b4d97e32.png">

**Comment by LoLyeah** [comment]
did you use the beta or stable? try the beta here http://plorkyeran.com/aegisub/
