### ISSUE TITLE
Repo development status

### ISSUE THREAD

**Issue by mhazim2** [Aegisub/Aegisub#205]
Want to know is this repo still has active development? since last official binaries on web was builded in 2014, i would like to know about aegisub support and compatibility with new OS and new video codecs in the future.

**Comment by mhazim2** [comment]
or maybe for who want the new updated aegisub can only `make` it from the source code? 
official binaries build was stopped?

**Comment by ilko-k** [comment]
the main branch is abandonned, see the fork here instead → https://github.com/wangqr/Aegisub

**Comment by FichteFoll** [comment]
See #214.
