### ISSUE TITLE
Race when pressing enter to set value in style editor

### ISSUE THREAD

**Issue by CoffeeFlux** [Aegisub/Aegisub#213]
```
23:39] Bunny: So basically, to get it to crash, I open the style, change a value and hit enter to update it
[23:40] Bunny: But it only seemed to happen when I hit enter without clicking away from the input box
```

Log: https://gist.github.com/Myaamori/488166af109575f15584a80bc6232c92

Video example: https://cdn.discordapp.com/attachments/541372421052170251/798410244673241098/2021-01-11_23-35-55.mkv

`Apply` is called after hitting enter, nulling that value and cancelling the dialog, but for some reason the event loop seems to continue to run this on Linux. This is almost certainly fixed with a simple null check there, but it would be good to make sure this is really a wx bug and file an issue upstream.

**Comment by TheOneric** [comment]
Should be identical to https://github.com/wangqr/Aegisub/issues/33#issuecomment-569534714 , which was already reported to and fixed by wx-upstream.

**Comment by CoffeeFlux** [comment]
I guess this is another case where linking against 3.0 on Linux is hurting us... I suspect we can't reasonably mandate 3.1 on Linux though. Either way, thanks for pointing that out.
