### ISSUE TITLE
Release new stable (3.4.0)

### ISSUE THREAD

**Issue by CoffeeFlux** [Aegisub/Aegisub#214]
Things are mostly wrapping up for 3.4.0, and I plan to cut the release by the end of the year. After chatting with arch, we'll be releasing out of TSTools/Aegisub going forward, since it's the repo I have full permissions on. Some quick notes:

The minimum OS version is bumped from the last release, which was 9 years ago. We now require Windows 10+ or MacOS 10.2. On Linux, packaging should hopefully be straightforward, as I've avoided requiring any dependency not available on Ubuntu LTS.

I am not merging in large, risky features in the interest of getting out a new, trustworthy stable after 9 years. This means, notably, that video panning will not be present and the installer will not include DependencyControl enabled by default. After 3.4.0 is out, we can start merging in bigger features.

I will also try to get any translation updates merged in, pending my ability to find someone to sanity check them.

Remaining tasks:

- [x] Merge https://github.com/TypesettingTools/Aegisub/pull/94
- [x] Merge https://github.com/TypesettingTools/Aegisub/pull/186
- [x] Disable DepCtrl installation by default
- [x] Change update-checker URL
- [x] Update repo URLs
- [x] Make sure to match ffi-experiments' vc redist version
- [x] Merge translation updates where possible

Actual release process:

- [x] Bump version numbers
- [x] Tag release
- [x] Run off builds
- [x] Write release post
- [x] Update site with build and release post
- [x] Post release to TypesettingTools/Aegisub
- [ ] Post release to Aegisub/Aegisub with a note for distros
- [x] Write something on the website explaining the Depctrl option in the installer
- [ ] Update Aegisub/Aegisub README
- [ ] Change update-checker version tag
- [ ] Close down Aegisub/Aegisub issues/PRs and archive repo

**Comment by seiya-git** [comment]
why 2.3.0 if latest is 3.2.2?

**Comment by CoffeeFlux** [comment]
Typo!

**Comment by OrakMoya** [comment]
So this project is still being maintained? I thought it wasn't since the last stable release was in 2014, and last commit to master was in 2019.

**Comment by CoffeeFlux** [comment]
The project was pretty dead for a while since the previous primary maintainer got busy with his full time job. I was recently given push access so there should be movement, though it's purely a weekend thing for me so I can't promise anything too wild.

**Comment by seiya-git** [comment]
@wangqr please make pull requests to this repo then

**Comment by samoht0** [comment]
Why not _first of all_ merge existing PR with vital stuff to fix compilation problems?
https://github.com/Aegisub/Aegisub/pull/134 https://github.com/Aegisub/Aegisub/pull/136 https://github.com/Aegisub/Aegisub/pull/137 https://github.com/Aegisub/Aegisub/pull/141 https://github.com/Aegisub/Aegisub/pull/174 https://github.com/Aegisub/Aegisub/pull/175

Also working PR for me and nice enhancements, I think:
https://github.com/Aegisub/Aegisub/pull/148 https://github.com/Aegisub/Aegisub/pull/192

**Comment by CoffeeFlux** [comment]
Because fixing the builds on MacOS/Linux doesn't actually solve the Windows build being horribly out of date. I've made the call that the way forward is a unified Meson build system, and I'm focused on the last mile of that instead of patching up Autotools. My goal here is to make sure the repo is maintainable long-term, not quickly merge a bunch of PRs.

After the components of this issue are sorted out, I intend to go through PRs to here and the TSTools fork and review everything still applicable.

**Comment by CoffeeFlux** [comment]
It seems likely the actual version bump will be `3.4.0` in the interest of not conflicting with wangqr's releases, which he marked as `3.3.x`.

**Comment by ilko-k** [comment]
oh, glad to see the devlopment is reviving. Will you improve ASSDraw as well someday ?

**Comment by FrankLidgad** [comment]
Excited that this is being resurrected. I just recently discovered this application and found it to be quite easy to use although time consuming. If I may make a suggestion, if you could add the option of adding markers on the audio wave form as you are playing the audio (with the use of a hotkey) one could then sync the subtitles without having to manually adjust each line. This could also be used in Karaoke mode as well to quickly align the words. Maybe something to think about for future versions. Also a repository for effects templates would be good to have. Thank you.

**Comment by ruixingw** [comment]
I see both you and other contributors are actively making commits  on https://github.com/TypesettingTools/Aegisub, which is very appreciated, Thank you! but I am wondering what is the relationship between `TypesettingTools/Aegisub` and this repo? Is `TypesettingTools/Aegisub` just a testground and the codes will eventually be merged into this repo, or should we track future Aegisub developments at `TypesettingTools/Aegisub` from now on and treat this repo here as abandoned?

**Comment by CoffeeFlux** [comment]
The TSTools branch should be merged in fairly soon - just a few remaining things to take care of. Further development should happen in this repo.

**Comment by ruixingw** [comment]
> The TSTools branch should be merged in fairly soon - just a few remaining things to take care of. Further development should happen in this repo.

Thanks for the clarification

**Comment by ghost** [comment]
anyone can build the 3.4.x please ?

**Comment by inkydragon** [comment]
@SFNasty 

https://github.com/TypesettingTools/Aegisub

And Artifacts (win & macOS): https://github.com/TypesettingTools/Aegisub/actions/runs/1332094026

**Comment by wdlkmpx** [comment]
The project surely needs a new maintainer

**Comment by begna112** [comment]
> The project surely needs a new maintainer

Ah yes, because it made lots of progress before. Go grab AegisubDC if you need something in the meantime.

**Comment by ilko-k** [comment]
Interesting, didn't know about it. Thanks.

**Comment by KerimDemirkaynak** [comment]
Will the new version include dark mode and interface improvements?

**Comment by arch1t3cht** [comment]
Do you offer to work on those improvements?

**Comment by 0tkl** [comment]
At the moment, some features are included in 3.3 (wangqr's fork) but not in 3.4 (I mean, master branch of TT/Aegisub). XAudio2 audio player from @arch1t3cht's fork works quite well on my device. Is there any blockers or roadmaps on these features?

**Comment by KerimDemirkaynak** [comment]
Hello, I would like to translate **Aegisub**'s website into **Turkish**. Can you send me the necessary files?

### My email address: aschannel111@gmail.com

**Comment by zefr0x** [comment]
> Hello, I would like to translate **Aegisub**'s website into **Turkish**. Can you send me the necessary files?

This is off topic, btw!

https://github.com/Aegisub/aegisite

Look at other pull requests to find out what you need to do.

**Comment by CoffeeFlux** [comment]
3.4.0 is out; any remaining tasks have been migrated to https://github.com/TypesettingTools/Aegisub/issues/240
