### ISSUE TITLE
Audio not working on 32bit external DAC

### ISSUE THREAD

**Issue by Setsugennoao** [Aegisub/Aegisub#215]
As the title suggests, when I use AegiSub with my DAC I have no audio and no waveform in the program. Once I go to the settings and change the format to 16bit/48KHz (from 32bit/384KHz) it works. What should I do? I really hate having to switch every time I open the program.
This is the first issue I open on GitHub so I'm sorry if I did something wrong.

**Comment by begna112** [comment]
For what it's worth, I don't have this issue using a Khadas Tone Board or a Topping D10. Both use native Windows drivers. So maybe if you've got some proprietary driver that's interfering. But also not sure why that would be, considering it's just ffmpeg doing the work. 

I am using https://github.com/Ristellise/AegisubDC though, until 3.4.0 is released. So maybe there's a difference.

**Comment by Setsugennoao** [comment]
Thanks a lot! It works
