### ISSUE TITLE
Libass work around in 3.2.2?

### ISSUE THREAD

**Issue by MegrezPines** [Aegisub/Aegisub#222]
I saw the libass option in the setting of Aegisub, but when I turned it on, the whole program crash (again and again and again that I have to reinstall the whole thing)
So how can I use libass in Aegisub? Note that when I checked the program file of Aegisub, I didn't see any file related to libass except one csri folder that is related to the default csri/xy-vsfilter-aegisub option in Aegisub.

**Comment by MadokaAyukawa** [comment]
I am able to set 3.2.2. to use libass.

**Comment by MegrezPines** [comment]
How did you do it without being crash?

**Comment by MadokaAyukawa** [comment]
Nothing special; it just doesn't crash for me when I set it to use libass.
