### ISSUE TITLE
YUV4MPEG: Video is not in a supported format, FFMpegsource: Video is not in a supported format

### ISSUE THREAD

**Issue by sprajagopal** [Aegisub/Aegisub#227]
Ubuntu 20.04, installed aegisub with apt-get. Version 3.2.2
This happens when I try to open mp4, avi videos. 
```
YUV4MPEG: Video is not in a supported format
FFMpegsource: Video is not in a supported format
```
I tried opening the same files with vlc, mpv, and the default gnome player: they all work with the file properly.
I saw forum posts with similar issues and no clear answers. If this is a common problem, is there any way to actually debug this?

Attaching the log window here:
[log_of_aegisub.txt](https://github.com/Aegisub/Aegisub/files/6136379/log_of_aegisub.txt)

Video source in options is set to ffmpegsource (it's the only option).
(not) Surprisingly a video from https://sample-videos.com/ opens fine in AegiSub. So clearly there's something wrong with my input video?

**Comment by wangqr** [comment]
Can you provide a sample video file?

**Comment by sprajagopal** [comment]
Trying to replicate. Unable to do so now. Something changed in my system. Closing the issue.
