### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by RfadnjdExt** [Aegisub/Aegisub#239]
Hi, when I want to install the Aegisub's dependencies, it gets error.
`brew install autoconf ffmpeg freetype gettext ffms2 fftw fribidi libass m4 `
Generates:
```
Error: Permission denied @ apply2files - /usr/local/lib/node_modules/peerflix/node_modules/ws/lib/.DS_Store
```
`brew install --devel --with-gc64 luajit`
```
Error: invalid option: --devel
```
`brew install --HEAD icu4c`
```
Error: No head is defined for icu4c
```
`brew install --HEAD --c++11 --with-icu4c boost`
```
Error: invalid option: --c++11
```
Thanks

**Comment by inkydragon** [comment]
This main repo is not active, waiting for big update. ( #214 )

You may use:
+ https://github.com/wangqr/Aegisub/releases/tag/v3.3.2
+ https://github.com/swigger/Aegisub-mac10.15
+ https://github.com/TypesettingTools/Aegisub
