### ISSUE TITLE
SRT parsing error, tried many format, no change (linux)

### ISSUE THREAD

**Issue by evanescente-ondine** [Aegisub/Aegisub#250]
Hi.
I read that I wasn't the first to encounter this issue but few do hence there is no ticket.
it says that there is parsing error at line 1 or 2.
I tried several things so it's time we come up with a systematic solution that doesn't include passing by an alternative software like SubtitleEdit, **which is stupid**.
I tried 6 times, by copying the first lines on LibreOffice, then saving in "text with choice of encodage", where I chose, in this order:
including mark of endianness: CR+LF, CR, LF
the same three, not including a mark of endianness.
either including or not the error happened at line 2 for CR+LF, 1 for CR, 2 for LF.

Now what next ?!
Yours.
content:
1
00:04:40 --> 00:04:41
Good evening professor.

2
00:04:42 --> 00:04:44
My darling.

3
00:04:44 --> 00:04:47
Good evening, Mother.

**Comment by garret1317** [comment]
that's not a valid srt, you need milliseconds as well
https://www.matroska.org/technical/subtitles.html#srt-subtitles

quick and dirty fix
```srt
1
00:04:40,000 --> 00:04:41,000
Good evening professor.

2
00:04:42,000 --> 00:04:44,000
My darling.

3
00:04:44,000 --> 00:04:47,000
Good evening, Mother.
```

**Comment by evanescente-ondine** [comment]
But VLC does read it... so VLC is wrong while it IS the viewer most people use... Splendid !!
And that file covers half the damn movie. I'mma make a new file from scratch, helped with the partial translation.
Thanks.
