### ISSUE TITLE
Issue on finding Latest Release

### ISSUE THREAD

**Issue by ShounenArgha** [Aegisub/Aegisub#261]
Sorry,people and devs,
is the latest release of aegisub the release at github/releases 2014 one?

**Comment by Kovinda** [comment]
There are forks which you can use like https://github.com/wangqr/Aegisub and https://github.com/Ristellise/AegisubDC

**Comment by ShounenArgha** [comment]
> There are forks which you can use like https://github.com/wangqr/Aegisub and https://github.com/Ristellise/AegisubDC

Thanks!
