### ISSUE TITLE
eyedropper is not working properly in linux

### ISSUE THREAD

**Issue by amanosatosi** [Aegisub/Aegisub#264]
when i used it, it works once. after that, it don't recording other frames. it just use same screenshot

**Comment by hitagiendmk2** [comment]
yeah, I have this problem too, I had to re-open Aegisub again if I want to make eyedropper worls every time I need to use that tool

**Comment by moex3** [comment]
It doesn't even work once for me on wayland. As a workaround I use this script bound to a hotkey.
`grim -g "$(slurp -p)" -t ppm - | convert - -format '%[pixel:p{0,0}]' txt:- | awk '! /^#/ {print $3}' | wl-copy -n`

**Comment by amanosatosi** [comment]
thanks [arch1t3cht](https://github.com/arch1t3cht). very cool.
