### ISSUE TITLE
Aegisub website is down, Where to functions list ?

### ISSUE THREAD

**Issue by foremtehan** [Aegisub/Aegisub#279]
Unfortunately Aegisub at the moment. I'm looking for a functions lists which starts with `{\` and ends with `}` for example `{fs\40}`

The problem is Aegisub UI apply setting to all lines but i'm looking for available functions to change each lines.

**Comment by Ereza** [comment]
https://aeg-dev.github.io/AegiSite/docs/3.2/ass_tags/
