### ISSUE TITLE
Blur text *and* border

### ISSUE THREAD

**Issue by ghost** [Aegisub/Aegisub#293]
Currently, per https://aeg-dev.github.io/AegiSite/docs/3.2/ass_tags/#:~:text=Blur%20edges text itself cannot be blurred if it has a border. So one has to choose between pleasingly soft but (depending on video frame) potentially illegible text:
![blurry](https://user-images.githubusercontent.com/13451773/197677055-63fcba27-bf14-472e-ab08-583a8388b8cf.jpg)
Or legible but harshly sharp text:
![sharp](https://user-images.githubusercontent.com/13451773/197677101-6dfdd388-87fd-4682-b5d6-d35588734121.jpg)
I propose that the text and border be given separate options for blurring, or that the blur option applies to both. It would allow for much more pleasant subtitles.

**Comment by moi15moi** [comment]
Like @hooke007 said to you here: https://github.com/mpv-player/mpv/issues/10784, open the issue on the libass repos, not this one.

[libass repos](https://github.com/libass/libass)

**Comment by ghost** [comment]
Will do.
