### ISSUE TITLE
How to get the file path in lua script?

### ISSUE THREAD

**Issue by tumuyan** [Aegisub/Aegisub#296]
I want to get the path of opened sub and video in lua script. 
but `path = aegisub.decode_path("?script") `   `path = aegisub.decode_path("?video") `  could only get the folder, not contains file name.

**Comment by arch1t3cht** [comment]
You can use `aegisub.decode_path("?script/" .. aegisub.file_name())`.

**Comment by tumuyan** [comment]
> You can use `aegisub.decode_path("?script/" .. aegisub.file_name())`.

Thank you, I get the sub file path now. but how to get the video or audio file name?

**Comment by arch1t3cht** [comment]
For those there are `aegisub.project_properties().video_file` and `aegisub.project_properties().audio_file`. If I'm not mistaken those are sometimes absolute paths and sometimes paths relative to the subtitle file, so to always get an absolute path you might need to check for that and if necessary prepend `?script/`.

**Comment by tumuyan** [comment]
Thank a lot, it works well

```
    script_path = aegisub.decode_path("?script/" .. aegisub.file_name())
    video_path = aegisub.project_properties().video_file
    audio_path =  aegisub.project_properties().audio_file

```

lua function refer
https://github.com/Aegisub/Aegisub/blob/master/src/auto4_lua.cpp
