### ISSUE TITLE
Inquiry on License

### ISSUE THREAD

**Issue by skaine** [Aegisub/Aegisub#301]
This issue has been resolved.

**Comment by frozenpandaman** [comment]
the aegisub police are coming to arrest you now

**Comment by skaine** [comment]
This issue has been resolved.

**Comment by frozenpandaman** [comment]
Awww, this was removed with the history deleted, that's no fun.

Here's an archived copy: https://archive.is/FWFSG  / [(mirror)](https://user-images.githubusercontent.com/7245874/233918017-16b63bbc-8699-4b21-bb45-cf3344d8d7d0.png)
