### ISSUE TITLE
Emoji error

### ISSUE THREAD

**Issue by datlmhg** [Aegisub/Aegisub#308]
I can't use some emoji, anyone know how to fix it?
![image](https://github.com/Aegisub/Aegisub/assets/86174857/d26459b0-ab96-44ec-8d93-71d3ab5ed073)

**Comment by CoffeeFlux** [comment]
This is a consequence of the subtitle renderer or the selected font, not Aegisub.

**Comment by datlmhg** [comment]
> This is a consequence of the subtitle renderer or the selected font, not Aegisub.

Not really, because a few days ago when I used calbri font, the emoiji still displayed, but now when I use calibri font again, the emoji is like this, Even now I use Times New Roman font, I still have the same problem, I don't know why
