### ISSUE TITLE
Aegisub App crashes in MacOS Sonoma

### ISSUE THREAD

**Issue by csjaugustus** [Aegisub/Aegisub#322]
When opening a .ass file in MacOS Sonoma, the app crashes with error:

**Program Error**
Oops, Aegisub has crashed!

There are no further details on the crash. Seems to be a compatibility problem, as it was fine before updating to Sonoma. I have heard others experiencing the same issue after updating to Sonoma.

![CleanShot 2023-09-28 at 16 01 37@2x](https://github.com/Aegisub/Aegisub/assets/61149391/352b06e6-f7d1-4312-adf0-7f85b5d1ed71)

**Comment by Clarab3** [comment]
Hi,
I have exactly the same issue and someone I know as well...

**Comment by knitweardHermes** [comment]
Same problem here...

**Comment by Nordisten** [comment]
I have the same problem, too. It always feels kind of risky to update macOS to a new version because it unfortunately almost always leads to some kind of a problem with Aegisub. Hopefully, there will be a solution to the current problem soon.

**Comment by bccaption2** [comment]
same here, any other fork can we use?

**Comment by arch1t3cht** [comment]
Is there any helpful error message when you run Aegisub from the command line? Does this also happen with newer forks like https://github.com/arch1t3cht/Aegisub ?

**Comment by bccaption2** [comment]
how can I install this fork ? (without dmg in the release)

**Comment by arch1t3cht** [comment]
> The macOS release was removed due to having broken library paths. Until the next release, Mac users can download fixed and updated builds on the actions page.

So you can either download one of the build artifacts on the actions page, or download the dmg from Release 09.

**Comment by Clarab3** [comment]
> 
> So you can either download one of the build artifacts on the actions page, or download the dmg from Release 09.

Where can I find this release please?

**Comment by Nordisten** [comment]
> Where can I find this release?

On this page: https://github.com/arch1t3cht/Aegisub/releases. Scroll down to Feature Release 09, click on Assets and download the correct .zip file.

**Comment by Clarab3** [comment]
Perfect! Thanks.

**Comment by bccaption2** [comment]
> > Where can I find this release?
> 
> On this page: https://github.com/arch1t3cht/Aegisub/releases. Scroll down to Feature Release 09, click on Assets and download the correct .zip file.

I got this error opening 09

Notes:
PC register does not match crashing frame (0x0 vs 0x1056EAA78)

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
Referenced from: <A8C1589C-7390-3B95-AC56-E8815CB173BA> /Applications/Aegisub.app/Contents/MacOS/libwx_osx_cocoau_gl-3.1.3.0.0.dylib
Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib' (no such file), '/usr/lib/libpng16.16.dylib' (no such file, not in dyld cache)Library not loaded: /usr/local/opt/libpng/lib/libpng16.16.dylib
Referenced from: <F62F8ECA-A767-34B5-BB5F-09444BE7F1E6> /Applications/Aegisub.app/Contents/MacOS/libwx_osx_cocoau_stc-3.1.3.0.0.dylib
Reason: tried: '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/opt/libpng/lib/libpng16.16.dylib' (no such file), '/usr/local/lib/libpng16.16.dylib
(terminated at launch; ignore backtrace)

**Comment by Nordisten** [comment]
> So you can either download one of the build artifacts on the actions page, or download the dmg from Release 09.

Brilliant! I just got a chance to test this briefly, and it actually seems to have done the trick (for me at least). Thanks a lot!

**Comment by Paulo1959** [comment]
"When opening a .ass file in MacOS Sonoma, the app crashes with error:"

- Same here, but I'm not familiar with these 'releases'. I am just a user (a heavier one, BTW). So, when we'll have a dmg update? Thanks

**Comment by csjaugustus** [comment]
> "When opening a .ass file in MacOS Sonoma, the app crashes with error:"
> 
> * Same here, but I'm not familiar with these 'releases'. I am just a user (a heavier one, BTW). So, when we'll have a dmg update? Thanks

My issue was resolved by following Nordisten's advice. Go to the releases link they gave and find the macOS release installer under Assets of Feature Release 09. This seems to have solved most people's issues. Please try and let me know how it works. If it's resolved I can close this issue.

**Comment by Paulo1959** [comment]
> > "When opening a .ass file in MacOS Sonoma, the app crashes with error:"
> > 
> > * Same here, but I'm not familiar with these 'releases'. I am just a user (a heavier one, BTW). So, when we'll have a dmg update? Thanks
> 
> My issue was resolved by following Nordisten's advice. Go to the releases link they gave and find the macOS release installer under Assets of Feature Release 09. This seems to have solved most people's issues. Please try and let me know how it works. If it's resolved I can close this issue.

It did work! Thanks alot!

**Comment by silalingopie** [comment]
It works, thank you so much y'all!

**Comment by rafatorres80** [comment]
Release 09 works!
