### ISSUE TITLE
I cant see subtitles but I see lines

### ISSUE THREAD

**Issue by Mulamuri** [Aegisub/Aegisub#325]
![image](https://github.com/Aegisub/Aegisub/assets/146960889/860f29b1-a328-410b-9c70-1111ab57d48b)
What Can I do?

**Comment by seiya-git** [comment]
Read the manual

**Comment by Mulamuri** [comment]
> Прочитайте руководство
Please, I havent much time. Can you simply give me the decision or show point of the manual?

**Comment by Madekuji** [comment]
From what I can see in the lines, the lines are commented. Make sure to uncheck the "Comment" for all of the lines that you want to appear.
