### ISSUE TITLE
{\an8} Issue when exporting into .srt

### ISSUE THREAD

**Issue by Valencart** [Aegisub/Aegisub#327]
Hi. So whenever I use the {\an8} tag it displays correctly inside Aegisub, but when I export the subtitles as an .srt file the tag is simply gone and I must manually include it again by editing it in through notepad. Any help to prevent this from happening would be extremely appreciated.

**Comment by arch1t3cht** [comment]
This is because the SRT format does not support this formatting.

**Comment by Valencart** [comment]
> This is because the SRT format does not support this formatting.
Thank you for replying. I see, then I suppose there's no easy way to keep the subtitle placement in the exported .srt file?

**Comment by FichteFoll** [comment]
Correct, the SRT format does not support overriding the subtitle positions.

**Comment by Valencart** [comment]
> Correct, the SRT format does not support overriding the subtitle positions.

Got it, thanks.

**Comment by po5** [comment]
Despite it not being part of the SRT format, many players (at least VLC and mpv) support it, and it's often used in subtitle files in the wild.
