### ISSUE TITLE
Input video cause crashed

### ISSUE THREAD

**Issue by dfjgxfckglvhij** [Aegisub/Aegisub#328]
I recently updated my mac to macOS Sonoma 14.0. (I'm not sure is this related to the issue) 
I found the problem that I can't input video into Aegisub. It works with ass documents, but when it loads the video, it crashed. 
I already reinstall the aegisub for several times, it does not help.
What should I do to solve this problem? Please help!

**Comment by dfjgxfckglvhij** [comment]
already found the solution in 322 :D

**Comment by jargalbat** [comment]
@dfjgxfckglvhij  what is the solution?

**Comment by dfjgxfckglvhij** [comment]
Please go to #322 and download the version of aegisub that is mentioned in 322, that is the solution. Hope ur problem can be solved as well :D
