### ISSUE TITLE
Audio suddenly stops working

### ISSUE THREAD

**Issue by IBellka** [Aegisub/Aegisub#331]
Hi, I tried to search for the problem on the forum but was unsuccessful. 
Yesterday I upgraded my MacOs to Sonoma software.
After opening Aegisub, I had a problem loading the video into the program (an error popped up). I read about the same problem on this forum and following the advice of other users I downloaded the latest version from future realase 9 (https://github.com/arch1t3cht/Aegisub/releases)
The problem is solved, the video loads but unfortunately there was another problem that is audio and sound waves work up to about 1-2 minutes of the video, then the sound waves are flat and there is no sound. 
The sliders do not help and this happens with every video.
Is anyone able to help me?

Thank you in advance for your time!

<img width="1137" alt="Zrzut ekranu 2023-11-21 o 11 16 04" src="https://github.com/Aegisub/Aegisub/assets/151625310/fed1f2af-f9ed-415c-a4ef-81e97aa600b2">

**Comment by arch1t3cht** [comment]
1. When reporting issues happening on my fork, you should make an issue on my fork instead. (Unless the issue also happens upstream, but you can't verify that here since upstream doesn't start at all for you.)
2. Does this also happen on the latest builds from https://github.com/arch1t3cht/Aegisub/actions?query=branch%3Afeature ?

**Comment by IBellka** [comment]
> 1. When reporting issues happening on my fork, you should make an issue on my fork instead. (Unless the issue also happens upstream, but you can't verify that here since upstream doesn't start at all for you.)
> 2. Does this also happen on the latest builds from https://github.com/arch1t3cht/Aegisub/actions?query=branch%3Afeature ?

Hi, really sorry, I didn't know. I'm totally new to this forum and didn't know how everything worked and where I should add my post.
+ I downloaded the program for macOS from this link that you wrote: https://github.com/arch1t3cht/Aegisub/actions/runs/6949146225 and it looks like the problem is solved. 
Thank you very much!!!
