### ISSUE TITLE
Display program error after loading video

### ISSUE THREAD

**Issue by lumos821** [Aegisub/Aegisub#334]
I updated to Mac OS Sonoma yesterday, but when I opened the application today, it showed a program error and prompted that the content was stored in the 'recovered' folder

**Comment by lumos821** [comment]
oh i solved from https://github.com/Aegisub/Aegisub/issues/322 !!!!
thank you guys~

**Comment by CoffeeFlux** [comment]
Should be solved with a new release before the end of the year.
