### ISSUE TITLE
The program doesn't open videos 

### ISSUE THREAD

**Issue by KaterinaBon** [Aegisub/Aegisub#337]
Hi! 
I've downloaded Aegisub, but it doesn't open any videos. I've tried shorter ones, still doesn't work, tried to reinstall the program, nothing. Tried to install older versions, didn't help. How can I fix that? 

It just closes the program and doesn't work. 

<img width="885" alt="Снимок экрана 2023-11-28 в 08 17 14" src="https://github.com/Aegisub/Aegisub/assets/152249521/f5acf50f-d13e-43e7-ac4c-271d89f641cb">

**Comment by KaterinaBon** [comment]
Thanks to the forum I've fixed the issue. Thank you for the program!

**Comment by cuong-nguyen-tpv-clv** [comment]
Hi @KaterinaBon. I meet same issue. Could you guide me how to fix it? I cannot access the forum now too...
Thanks in advance
