### ISSUE TITLE
Aegisub won't run on Windows 11: Aegisub has crashed while starting up!

### ISSUE THREAD

**Issue by zidniahmadm** [Aegisub/Aegisub#346]
I have used aegisub many times, it just so happens that my Windows PC has just been reinstalled and uses Atlas OS. But aegisub cannot be run even if using administrator permission.
![Uploading 20240208_225914.jpg…]()

Error message: the last startup step attempted was: create main window

**Comment by doesntmattervoid** [comment]
having win 10 ghost spectre, everythings fine, on default 11 everythings good. The reason of this bug is probably the atlasos
