### ISSUE TITLE
"Timing Subtitles to Audio" docs page has incorrect information

### ISSUE THREAD

**Issue by FravBox** [Aegisub/Aegisub#350]
https://aegisub.org/docs/latest/timing/

The main audio view has a screenshot of that view with all the buttons labeled with numbers.
The text with numbered bullets below explains all the buttons, except most of the buttons are incorrectly explained - the numbers are not associated with the correct explainers.

**Comment by FichteFoll** [comment]
The docs repository is actually at https://github.com/Aegisub/aegisite.

**Comment by FravBox** [comment]
cross-posted issue here: https://github.com/Aegisub/aegisite/issues/36
