### ISSUE TITLE
Opening video results in program closing 

### ISSUE THREAD

**Issue by FloydPowers** [Aegisub/Aegisub#352]
Hello,

After installing Aegisub on a new Ubuntu 24.04 system, I have found that attempting to open a video in Aegisub results in a crash.

Steps to reproduce (ubuntu 24.04, 3.3.3-snap5a):

- Select and open any video file with Video -> Open Video

After doing this, the program closes.

Please let me know if there's any more information I can provide.

Thank you,
Floyd Powers

**Comment by edward-hong** [comment]
I have same issue on 22.04

**Comment by viniciusmi00** [comment]
Program freezes on macOS.
Sonoma 14.5 (Intel) 32GB RAM (~1.41 - 1.43 GB used by Aegisub when it freezes)

**Comment by CoffeeFlux** [comment]
I'm assuming most FFmpeg-related crashes are fixed on the new stable, 3.4.0.
