### ISSUE TITLE
Aegisub installed via Flatpak

### ISSUE THREAD

**Issue by Whitehachi** [Aegisub/Aegisub#354]
I'm trying to import a video of MKV, but I'm getting an error message.
```
YUV4MPEG: video is not in a supported format.
FFmpegSource: video is not in a supported format.
```

When I try to import some videos from MKV to MP4, I get an error message
```
YUV4MPEG: video is not in a supported format.
FFmpegSource: Failed to open video track: Insanity detected: decoder returned an empty frame
```

Why Do I Get an Error When I Import Videos?

Aegisub installed via Flatpak.

**Comment by seiya-git** [comment]
Aegisub from Flatpak uses wangqr fork (not this one)
see: #336
