### ISSUE TITLE
aegisub hangs after i select a video

### ISSUE THREAD

**Issue by ericjamesonline** [Aegisub/Aegisub#357]
title says it all. it gave an error the first time i tried to open a video, then afterwards it hung.

app version: 3.2.2
OS: macOS 14.5

**Comment by cuong-nguyen-tpv-clv** [comment]
I have same issue. @EricE549X Have you solved it?

**Comment by ericjamesonline** [comment]
idk if it will be solved since this repo hasn't been updated in a while

**Comment by ericjamesonline** [comment]
however, the issue was fixed at https://github.com/wangqr/Aegisub/releases/tag/v3.3.3

**Comment by cuong-nguyen-tpv-clv** [comment]
I've already fixed it. Thank you!
