### ISSUE TITLE
YUV4MPEG: video is not in a supported format. FFmpegSource: Failed to index: Truncated input file

### ISSUE THREAD

**Issue by SheherazadeL** [Aegisub/Aegisub#358]
Hi, 
I have an issue opening a mkv file in aegisub 3.2.2

As I put the file in the app I have this message appearing : **YUV4MPEG: video is not in a supported format. FFmpegSource: Failed to index: Truncated input file**

It's been a while since I last used aegisub, but I believe I have used this format without any issues in the past so I'm not sure what I did wrong. Also, my friend tried opening the same file on his computer (windows11) and it's working great .. 

I'm using macOS Ventura 13.6.6 (22G630)

Here are the video settings if that can help : 

Format                                   : Matroska

ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Profil du format                         : High@L5
Paramètres du format                     : CABAC / 6 Ref Frames
Paramètres du format, CABAC              : Oui
Paramètres du format, RefFrames          : 6 images
Identifiant du codec                     : V_MPEG4/ISO/AVC
Durée                                    : 2 h 29 min
Débit nominal                            : 6 000 kb/s
Largeur                                  : 1 920 pixels
Hauteur                                  : 1 080 pixels
Format à l'écran                         : 16/9
Type d'images/s                          : Constant
Images par seconde                       : 24,000 Im/s
Espace de couleurs                       : YUV
Sous-échantillonnage de la chrominance   : 4:2:0
Profondeur des couleurs                  : 8 bits
Type de balayage                         : Progressif
Bits/(Pixel*Image)                       : 0.121
Bibliothèque utilisée                    : x264 core 164

Default                                  : Oui
Forced                                   : Non
Gamme de couleurs                        : Limited
Coordonnées de chromaticité              : BT.709
Caractéristiques du transfert            : BT.709
Coefficients de la matrice               : BT.709

Let me know if there's any more information I can provide.

Thank you, :)

**Comment by emaxx18** [comment]
facing the same issue :(

**Comment by CoffeeFlux** [comment]
I'm assuming most FFmpeg-related crashes are fixed on the new stable, 3.4.0.
