### ISSUE TITLE
Can't open video on Mac

### ISSUE THREAD

**Issue by wenhaoquestion** [Aegisub/Aegisub#372]
![Screenshot 2024-09-11 at 15 36 44](https://github.com/user-attachments/assets/f6aa8d41-e623-4389-9220-d372f718f10e)
This what will happen when I trying to load a video in the Aegisub.
My mac is m1 pro and in MacOS Sequoia 15.1 Beta 3

**Comment by Zee-999** [comment]
Same issue here on Mac. Have you solved it?

**Comment by chenbin0522** [comment]
https://github.com/Aegisub/Aegisub/issues/322

**Comment by wenhaoquestion** [comment]
No still can not open
________________________________
发件人: Zee-999 ***@***.***>
发送时间: 2024年9月17日 1:01
收件人: Aegisub/Aegisub ***@***.***>
抄送: wenhaoquestion ***@***.***>; Author ***@***.***>
主题: Re: [Aegisub/Aegisub] Can't open video on Mac (Issue #372)


Same issue here on Mac. Have you solved it?

―

**Comment by LDL5216** [comment]
I have the same issue, but the method to solve it is quite weird... What I do is double cilck the file you want instead cilck on the open button. Hope this can help you.

**Comment by CoffeeFlux** [comment]
I'm assuming most FFmpeg-related crashes are fixed on the new stable.
