### ISSUE TITLE
Can't do hardsubs because "There is no function named 'ffvideosource'"

### ISSUE THREAD

**Issue by HaleyHalcyon** [Aegisub/Aegisub#374]
I can't put hardsubs on my video using Aegisub because Avisynth won't cooperate.

Which version of Avisynth is intended to be used for which version of Aegisub? I looked around and I don't think Avisynth has been updated for over a decade.

Here's the output:
```
D:\Downloads\Aegisub\aegisub-fork-9212>"D:\Downloads\Aegisub\aegisub-3.2.2-portable-64\encode\x264.exe" --crf 18 --ref 10 --bframes 10 --merange 32 --me umh --subme 10 --trellis 2 --direct auto --b-adapt 2 --partitions all -o "D:\Videos\hardsub.mkv" "D:\Downloads\yt\hardsub.avs"
avs [error]: Script error: There is no function named 'ffvideosource'.
(D:\Downloads\yt-dlp\hardsub.avs, line 2)
x264 [error]: could not open input file `D:\Downloads\yt\hardsub.avs'
```

**Comment by CoffeeFlux** [comment]
If you're looking to hardsub, you'll need to use an ASS renderer in Avisynth (xy-subfilter or libass). Aegisub is an editor, and doesn't actually render the subtitles itself.

**Comment by HaleyHalcyon** [comment]
> If you're looking to hardsub, you'll need to use an ASS renderer in Avisynth (xy-subfilter or libass). Aegisub is an editor, and doesn't actually render the subtitles itself.

That doesn’t answer my question: Which version of Avisynth is intended to be used for which version of Aegisub? I looked around and I don't think Avisynth has been updated for over a decade.

**Comment by CoffeeFlux** [comment]
In your command above you're invoking x264, and it just happens to live within the aegisub folder. I'm happy to help if I can, but I don't understand how Aegisub is involved - maybe I'm misunderstanding what you're trying to do? Even a decade-old Avisynth version should be able to render ASS just fine.

That said, it looks like your system avisynth install is missing the appropriate plugin(s). http://avisynth.nl/index.php/FFmpegSource

**Comment by HaleyHalcyon** [comment]
I tried following this documentation https://aegisub.org/docs/latest/attaching_subtitles_to_video/#hardsubbing-with-avisynth but couldn't find a version of AviSynth that encoded the video correctly.

If this documentation is outdated, can I learn an updated way to encode hardsubs?

**Comment by arch1t3cht** [comment]
The modern way to hardsub is using mpv, for example:

```
mpv --no-config <video file> -o <output file> --ovc=libx264 --ovcopts=preset=slow,crf=18
```

Of course you can customize the video encode option or encode to a different format if you want, see the [mpv manual](https://mpv.io/manual/master/) for more information.
