### ISSUE TITLE
Detect and Change the Font

### ISSUE THREAD

**Issue by MrFanservice-png** [Aegisub/Aegisub#379]
How do I detect/get the name and change the font of subtitles? Like this, for example:
![Screenshot (11)](https://github.com/user-attachments/assets/a409376c-036f-45b7-b6cc-6b37fdbfb8c6)

**Comment by FichteFoll** [comment]
There is no `\fn` tag in this line, so the font name is sourced from the style. You can view and edit the style of the current line by pressing the "Edit" button next to the style dropdown (which reads "title" here). Note that this will of course affect *all* lines using this style.
