### ISSUE TITLE
Add Hotkey failed using Chinese Language

### ISSUE THREAD

**Issue by Sofronio** [Aegisub/Aegisub#63]
When I add a new hotkey, aegisub will save it.
But when I open the hotkey setting again, the new hot key is classified as a new one.
For example, if I add a hotkey "Ctrl-Left" under "Audio", which it'll be displayed as "音频" in Chinese,
the second time I open hotkey setting, there will be two "音频" hotkey node.
I opened the hotkey.json, and the new hotkey is not inside "Audio" node, but inside "音频" node, as shown:

```
...
	"Audio" : {
		"app/toggle/global_hotkeys" : [
			"Ctrl-KP_Multiply"
		],
		...
		"time/prev" : [
			"Left",
			"Z"
		]
	},		
	"音频" : {
		"time/prev" : [
			"Ctrl-Left"
		]
	}
}
```

I think aegisub saved the json node using display language,

**Comment by Sofronio** [comment]
I tried to use bug tracker on aegisub.org, but it's not working.

**Comment by computerfan** [comment]
This issue should have been solved by #25 .

**Comment by Sofronio** [comment]
Thank you!

**Comment by CoffeeFlux** [comment]
Yeah this should have already been fixed. We desperately need to release a new stable so that people can actually make use of this, but I think that's outside the bounds of this issue and it ought to be closed. If the issue is present in a trunk build, then feel free to reopen.
