### ISSUE TITLE
Incorrect CPS for Vietnamese language

### ISSUE THREAD

**Issue by nimbeus** [Aegisub/Aegisub#67]
![image](https://user-images.githubusercontent.com/39670420/40585366-8912d710-61db-11e8-92cf-c8f11e2376fe.png)

**Comment by lorilay7** [comment]
I think this is not the character counter, it's characters per second for when you're doing dubbing

**Comment by nimbeus** [comment]
Ah sorry I'll edit the title. But that sentence is still definitely not 22 characters/second.

**Comment by nimbeus** [comment]
Stupid me. I figured out what I did wrong. The time indicators were too close to each other and I didn't notice. I'll close this issue now. Sorry about any confusion I've caused.
