### ISSUE TITLE
Mac: Audio sliders are unreliable

### ISSUE THREAD

**Issue by akx** [Aegisub/Aegisub#74]
On Aegisub 3.2.2 on macOS 10.13.4, the three audio sliders are unreliable; trying to interact with them seems to bring the relevant value to the maximum or minimum.

It also seems that they are visually missing their tracks – and a zero-size track would probably lead to the behavior I'm seeing.

<img width="147" alt="screen shot 2018-06-11 at 17 44 25" src="https://user-images.githubusercontent.com/58669/41238651-2186d194-6d9f-11e8-8fa6-c3bb7548b05e.png">

**Comment by lorilay7** [comment]
You should just update to r8942.

**Comment by akx** [comment]
Thanks, I'll give that a shot! It's not very clear on the Aegisub.org site. :)

**Comment by akx** [comment]
Yup, that fixed it. Thank you!

**Comment by ewels** [comment]
Ah you just made my day - thank you!

**Comment by JoanaKnobbe** [comment]
You saved me! Thanks :)
