### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by darealshinji** [Aegisub/Aegisub#76]
Version 3.2.2 was released 4 years ago and quite some changes have been made since then. A new release may be good I think, especially since most Linux distros will only add official releases to their packaging systems and Windows and Mac users don't have to search for prebuilt snapshots from the git master branch.

**Comment by FledgeXu** [comment]
There only are upcoming version.
You should check out this : http://plorkyeran.com/aegisub/

**Comment by Play38** [comment]
Where can I download the prebuilt version? like I mean a working Aegisub version.

**Comment by Asday** [comment]
:+1: for this, as I remember using AegiSub in the past, and looking at the website with all its broken links and nearly 5 year old latest release, I was sad that it had died.

Turns out I was wrong.

**Comment by aniolm9** [comment]
Hello, I'm the Debian Maintainer for Aegisub [[0]]. Currently we need to apply 16 patches [[1]] in order to make Aegisub work, and it makes quite difficult the package maintenance. Most of these patches are from commits done after the last release.

We would really appreciate a new release as it would ease our job a lot. If you need any help with the release process just let me know and I'll do my best.

[0]: https://nm.debian.org/person/amarti
[1]: https://salsa.debian.org/debian/aegisub/tree/debian/sid/debian/patches

**Comment by darealshinji** [comment]
> 
> 
> Hello, I'm the Debian Maintainer for Aegisub [[0](https://nm.debian.org/person/amarti)]. Currently we need to apply 16 patches [[1](https://salsa.debian.org/debian/aegisub/tree/debian/sid/debian/patches)] in order to make Aegisub work, and it makes quite difficult the package maintenance. Most of these patches are from commits done after the last release.
> 
> We would really appreciate a new release as it would ease our job a lot. If you need any help with the release process just let me know and I'll do my best.

A new official release in Debian and therefore all distros based upon it would be awesome (I'm sure many other distros are waiting for a new release too). Can't you just release a snapshot or is that against Debian guidelines? Anyway, personally I would like it though if the developers would go through at least a few of the open pull requests and issues before making an official release.

**Comment by aniolm9** [comment]
> A new official release in Debian and therefore all distros based upon it would be awesome (I'm sure many other distros are waiting for a new release too). Can't you just release a snapshot or is that against Debian guidelines?

It is against the Debian guidelines. I can't release 3.2.3 if it does not exist in upstream. When I packaged the current version (3.2.2+dfsg-4) I tried to clone the master branch and package it, but it was rejected, so I had to add the patches one by one.

> Anyway, personally I would like it though if the developers would go through at least a few of the open pull requests and issues before making an official release.

I'm not an experienced C++ developer, but I can try to help with that.

**Comment by aniolm9** [comment]
Besides @tgoyne who has merge permissions?

**Comment by darealshinji** [comment]
> Besides @tgoyne who has merge permissions?

There are two others that might be able to do it: https://github.com/orgs/Aegisub/people

**Comment by aniolm9** [comment]
Thanks!

I think it would be a good idea to also give merge and release permissions to somebody who has more time to maintain Aegisub. It would be a pity that this project dies...

**Comment by seiya-git** [comment]
@tgoyne, do you plan make new release soon?

**Comment by LuRenJiasWorld** [comment]
In addition, the build method of MacOS in README.md is no longer work at MacOS Catalina, please consider updating it. Thanks.

**Comment by PureTryOut** [comment]
Why is this closed? As far as I can see, the last release is from 2014. That is _10 years ago_!

**Comment by arch1t3cht** [comment]
https://aegisub.org/blog/aegisub-3.4.0-released

**Comment by JokerQyou** [comment]
@arch1t3cht Maybe the README of this repo should be updated to reflect that development has moved to https://github.com/TypesettingTools/Aegisub ? Or pin a related issue that contains this information. Otherwise people would constantly get confused (and would still post issues in this repo).

**Comment by Fuseteam** [comment]
Huh never noticed this repo is a fork of https://github.com/TypesettingTools/Aegisub

**Comment by FichteFoll** [comment]
It is actually not. Aegisub/Aegisub is the original repo (after being moved here from SVN) but the fork direction has been inverted at some point by GitHub support ~~at the request of the owner(s) of the repo because development will continue on the TypesettingTools repo~~.

Edit: crossed out incorrect statements

**Comment by CoffeeFlux** [comment]
I feel obligated to mention that it was not at my (or to my knowledge, anyone's) request. It just showed up one day.
