### ISSUE TITLE
Problem building current git source when using the bundled LuaJIT

### ISSUE THREAD

**Issue by iiv3** [Aegisub/Aegisub#87]
After downloading the current git version, running `autogen.sh`, `configure` and `make` I get the following error:
```
cd /tmp/aegisub-3.2.100/aegisub-3.2.100_GIT20180807_0524/src/libresrc; ./vendor/luajit/src/host/minilua /tmp/aegisub-3.2.100/aegisub-3.2.100_GIT20180807_0524/tools/respack.lua ../bitmaps/manifest.respack bitmap.cpp bitmap.h
/bin/sh: ./vendor/luajit/src/host/minilua: No such file or directory
make: *** [/tmp/aegisub-3.2.100/aegisub-3.2.100_GIT20180807_0524/src/libresrc/Makefile:19: /tmp/aegisub-3.2.100/aegisub-3.2.100_GIT20180807_0524/src/libresrc/bitmap.h] Error 12
```
The `minilua` programs seems to be properly built and marked executable before attempting to use it.
The problem seems to be that `configure` assigns `srcdir="."` instead of full path. Then the program is called from sub/subdirectory.

The `"."` value is assigned by the `configure` itself, when we have same physical and logical path (aka, no symlinks in the path). It does so even when using explicit `configure --subdir=/tmp/aegisub-3.2.100/aegisub-3.2.100_GIT20180807_0524`
Manually editing `Makefile.inc` to put the full path, allows the compilation to continue.

Since the git source does not come with `configure`, and `configure.ac` handles the `srcdir` with a single line `AC_CONFIG_SRCDIR([src/main.cpp])`. 
It looks like this is the intended behavior on autoconf side.

I'm not really sure how this should be fixed.
There is $abs_srcdir, however that is exported only to the `Makefile`. Inside `configure` only the internal variable `$ac_abs_scrdir` exists.

I believe I have fairly recent auto-tools: autoconf-2.69,  automake-1.16.1.

**Comment by szc126** [comment]
+1

> The `minilua` programs seems to be properly built and marked executable before attempting to use it.
> Manually editing `Makefile.inc` to put the full path, allows the compilation to continue.

I had to run `make` in `/vendor/luajit` first. Although, it still wouldn't build for me, and I ended up installing (Debian) `luajit` and `libluajit-5.1-dev`, which produced a working build.

Also, the output of `./configure` wrote `LuaJIT: bundled` regardless of the final value of `BIN_LUA` in `Makefile.inc`. Is this the desired output? (→new issue?)
