### ISSUE TITLE
Bug tracker and forums appear to be down

### ISSUE THREAD

**Issue by davidsnyder** [Aegisub/Aegisub#89]
http://forum.aegisub.org/ hangs and http://devel.aegisub.org/ gives a 502 Bad Gateway.

**Comment by SGalazzo** [comment]
Seeing is how we can't get to the main page, and that the read-me doesn't include the IRC server/channel, would it be possible to get that information somewhere as well?

**Comment by Leinad4Mind** [comment]
When fixing this maybe they can add https to it.

**Comment by 8day** [comment]
They have been down for quite some time: https://github.com/Aegisub/Aegisub/issues/70
