### ISSUE TITLE
[Solved] Unable to apply karaoke templates

### ISSUE THREAD

**Issue by ilko-k** [Aegisub/Aegisub#96]
> Runtime error in template code: Expected 1 arguments, got 2
Code producing error: ci = { 0 }; cn = _G.unicode.len(orgline.text_stripped:gsub(" ",""))

This error occurs in the v88+ builds, at least (I didn't try any earlier build). v3.2.2 is ok for both x32/x64 versions. Maybe an issue in the lua interpreter ?

**Comment by FichteFoll** [comment]
Use `_G.unicode.len(orgline.text_stripped:gsub(" ","")[1])`. `gsub` returns two values which are implicitly unpacked when used as the sole (or last?) argument of a function call.

Yeah, I've had my fun with that before. I'm not sure what exactly changed between trunk/master builds and the last release, though.

**Comment by FichteFoll** [comment]
Hm yeah, can reproduce. I just checked my IRC logs again and the fix to this is to instead wrap the expression in parens, i.e. `_G.unicode.len((orgline.text_stripped:gsub(" ","")))`.

**Comment by ilko-k** [comment]
Oh that did the job, thank you very much 😃

**Comment by FichteFoll** [comment]
You can close issues you opened yourself. :wink:
